version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/express-app
permissions:
  - object: /home/ec2-user/express-app/tmpfiles
    mode: 644
    acls:
      - "d:u::rwx"
      - "d:g::rwx"
      - "d:o::rwx"
    owner: ec2-user
    type:
      - directory
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 900
      runas: ec2-user
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 900
      runas: ec2-user
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 900
      runas: ec2-user
