version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/express-app
hooks:
  BeforeInstall:
    - location: script/before_install.sh
      timeout: 900
      runas: ec2-user
  ApplicationStart:
    - location: script/application_start.sh
      timeout: 900
      runas: ec2-user
